# Generated by Django 3.2.5 on 2021-08-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('growth', models.IntegerField()),
                ('base_interest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.CharField(max_length=2048)),
                ('photo', models.CharField(max_length=2048)),
                ('avg_likes', models.IntegerField()),
                ('avg_views', models.IntegerField(blank=True, null=True)),
                ('subs', models.IntegerField()),
                ('network', models.CharField(max_length=20)),
                ('wellness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('description', models.CharField(max_length=2048)),
                ('blogers', models.ManyToManyField(to='api.Bloger')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2048)),
                ('title', models.CharField(max_length=512)),
                ('date', models.DateField()),
                ('likes', models.IntegerField()),
                ('views', models.IntegerField(blank=True, null=True)),
                ('comm_positive', models.FloatField()),
                ('comm_neutral', models.FloatField()),
                ('comm_negative', models.FloatField()),
                ('bloger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bloger')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.trip')),
            ],
        ),
    ]
