# Generated by Django 3.2.5 on 2021-08-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_title_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='photo',
            field=models.CharField(default='nometa.xyz', max_length=2048),
            preserve_default=False,
        ),
    ]
