# Generated by Django 3.2.5 on 2021-08-21 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attraction_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='refuse_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 10, 0, 20, 698407)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloger',
            name='refused',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
