# Generated by Django 3.2.5 on 2021-08-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210821_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='Kek', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='blogers',
            field=models.ManyToManyField(blank=True, to='api.Bloger'),
        ),
    ]
