# Generated by Django 3.2.5 on 2021-08-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210821_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='growth',
            new_name='curr_interest',
        ),
    ]
